import {Component, ViewEncapsulation, OnInit} from '@angular/core';
import {FormGroup, AbstractControl, FormBuilder, Validators} from '@angular/forms';
import {SpinnerService} from "../../shared/services/spinner/spinner.service";
import {EmailValidator} from "../../shared/validators/email.validator";
import {UserService} from '../services/user.service';
import {NotificationsService} from 'angular2-notifications';

@Component({
  selector: 'app-forgotten',
  encapsulation: ViewEncapsulation.None,
  templateUrl: './forgotten.component.html',
  styleUrls: ['./forgotten.component.scss']
})

export class ForgottenComponent implements OnInit {

  public form:FormGroup;
  public email:AbstractControl;
  public submitted:boolean = false;

  constructor(fb:FormBuilder, private spinnerService: SpinnerService, 
              private notificationsService: NotificationsService, private userService: UserService) {
    this.form = fb.group({
      'email': ['', Validators.compose([Validators.required, EmailValidator.validate])]
    });

    this.email = this.form.controls['email'];
  }

  ngOnInit():void {
    this.spinnerService.show();
  }

  public ngAfterViewInit(): void {
    this.spinnerService.hide(1000);
  }

  public onSubmit(values: Object):void {
    this.submitted = true;
    if (this.form.valid) {

      this.spinnerService.show();
      let mail = values['email'];

      this.userService.sendNewAutoGeneratedPassword(mail)
        .subscribe(response => {
          console.log(response.json().success);
          if(response.json().success === false) {
            this.notificationsService.error('No such email registered', 'Try again');
            setTimeout(() => {this.form.reset(); }, 500);
            this.spinnerService.hide();
          } else {
            this.notificationsService.success(
                'Successfully changed password!',
                'You can check it out in your mail!'
            )
            this.spinnerService.hide();
            this.form.reset();            
          }
        }, (err) => {
          console.log('doesnt catch anything');
        });
    }
  }
}
