import {Component, ViewEncapsulation, OnInit} from '@angular/core';
import {FormGroup, AbstractControl, FormBuilder, Validators} from '@angular/forms';
import {Router} from '@angular/router';
import {SpinnerService} from "../../shared/services/spinner/spinner.service";
import {EmailValidator} from "../../shared/validators/email.validator";
import {UserService} from '../services/user.service';
import {AuthService} from '../../shared/services/auth';
import {NotificationsService} from 'angular2-notifications';

@Component({
  selector: 'app-forgotten',
  encapsulation: ViewEncapsulation.None,
  templateUrl: './forgotten.component.html',
  styleUrls: ['./forgotten.component.scss']
})

export class ForgottenComponent implements OnInit {

  public form:FormGroup;
  public email:AbstractControl;
  public submitted:boolean = false;

  constructor(fb:FormBuilder,
              private appRouter: Router,
              private authService: AuthService,
              private spinnerService: SpinnerService,
              private notificationsService: NotificationsService, private userService: UserService) {
    this.form = fb.group({
      'email': ['', Validators.compose([Validators.required, EmailValidator.validate])]
    });

    this.email = this.form.controls['email'];
  }

  ngOnInit():void {
    this.spinnerService.show();

    if(this.authService.isLoggedIn()){
      this.appRouter.navigateByUrl('/dashboard');
    }
  }

  public ngAfterViewInit(): void {
    this.spinnerService.hide(1000);
  }

  public onSubmit(values: Object):void {
    this.submitted = true;
    if (this.form.valid) {

      let mail = values['email'];

      this.userService.sendNewAutoGeneratedPassword(mail)
        .subscribe(response => {

          if(response.json().success === false) {
            this.notificationsService.error('No such email registered', 'Try again');
            setTimeout(() => {this.form.reset(); }, 500);

          } else {
            const successTitle = 'uccessfully changed password!';
            const successMessage = 'You can check it out in your mail!';
            this.notificationsService.success(successTitle, successMessage);

            this.form.reset();
            setTimeout(() => this.appRouter.navigateByUrl('/login'), 500);
          }
        }, (err) => {
          const errorTitle = "Oops! Something went wrong..";
          const errorMessage = err.json().message;
          this.notificationsService.error(errorTitle, errorMessage);
        });
    }
  }
}
